### ISSUE TITLE
RuntimeError: The size of tensor a (91) must match the size of tensor b (7) at non-singleton dimension 0

### ISSUE THREAD

**Issue by buloseshi** [ver0z/Deformable-DETR-#1]
### When I try to train custom dataset, the following error occurs. After start training it will occurs. Could you please tell me where was wrong?

Start training
Traceback (most recent call last):
  File "main.py", line 327, in <module>
    main(args)
  File "main.py", line 277, in main
    model, criterion, data_loader_train, optimizer, device, epoch, args.clip_max_norm)
  File "/mnt/e/opencv/Deformable-DETR--main1/Deformable-DETR--main/engine.py", line 56, in train_one_epoch
    optimizer.step()
  File "/home/bugs/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/bugs/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/bugs/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/optim/adamw.py", line 104, in step
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (91) must match the size of tensor b (7) at non-singleton dimension 0

**Comment by ver0z** [comment]
I guess the tensor 91 is the tensor for coco dataset and tensor 7 is yours, so you must change the number to your dataset.

**Comment by buloseshi** [comment]
> I guess the tensor 91 is the tensor for coco dataset and tensor 7 is yours, so you must change the number to your dataset.

I guess so, Can you guide me on how to modify 91? I'm new to this. Thanks a lot!!!!

**Comment by ver0z** [comment]
For this case I followed the issues of original DETR [https://github.com/facebookresearch/detr/issues/9](url) for custom dataset, I could understand that the mismatch of tensor I just changed the number of classes in deformable_detr.py lines 445 ahead, this might be your case.

**Comment by buloseshi** [comment]
Thanks!! , I solved this, Just modify the hubconf.py, pretrained models. The default num_classes is 91.

**Comment by SuperVirtue** [comment]
Sorry, I have the same problem, but I don't see hubconf Py file
